import jsPDF from 'jspdf';
import 'jspdf-autotable';
import { CompanySettings } from '@/types/asset';
import { logger } from '@/lib/logger';

declare module 'jspdf' {
  interface jsPDF {
    autoTable: (options: any) => jsPDF;
  }
}

interface TableColumn {
  header: string;
  dataKey: string;
  width?: number;
}

interface SummaryStatistic {
  label: string;
  value: string | number;
}

interface ReportConfig {
  title: string;
  subtitle?: string;
  reportType?: string;
  companySettings: CompanySettings;
  columns: TableColumn[];
  data: any[];
  summaryStats?: SummaryStatistic[];
  orientation?: 'portrait' | 'landscape';
  headerColor?: [number, number, number];
}

/**
 * Unified Professional PDF Report Generator
 * Applies consistent professional formatting across all reports
 */
export const generateUnifiedReport = (config: ReportConfig): void => {
  const {
    title,
    subtitle,
    reportType,
    companySettings,
    columns,
    data,
    summaryStats,
    orientation = 'landscape',
    headerColor = [41, 128, 185] // Professional blue
  } = config;

  // Create new PDF document with specified orientation
  const doc = new jsPDF(orientation);

  // Add company logo if available
  if (companySettings.logo) {
    try {
      doc.addImage(companySettings.logo, 'JPEG', 20, 10, 30, 20);
    } catch (error) {
      logger.warn('Could not add logo to PDF', { context: 'UnifiedReportGenerator' });
    }
  }

  // Add company information
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text(companySettings.companyName || 'Asset Management System', 60, 20);

  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  let headerY = 28;

  if (companySettings.address) {
    doc.text(companySettings.address, 60, headerY);
    headerY += 7;
  }
  if (companySettings.phone) {
    doc.text(`Phone: ${companySettings.phone}`, 60, headerY);
    headerY += 7;
  }
  if (companySettings.email) {
    doc.text(`Email: ${companySettings.email}`, 60, headerY);
  }

  // Add report title and metadata
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text(title, 20, 60);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Generated on: ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}`, 20, 68);

  if (reportType) {
    doc.text(`Report Type: ${reportType}`, 20, 74);
  }

  if (subtitle) {
    doc.setFontSize(12);
    doc.setFont('helvetica', 'italic');
    doc.text(subtitle, 20, 80);
  }

  // Prepare table configuration
  const tableColumns = columns.map(col => col.header);
  const tableData = data.map(row => 
    columns.map(col => {
      const value = row[col.dataKey];
      if (value === null || value === undefined) return '-';
      if (typeof value === 'number') return value.toFixed(2);
      if (value instanceof Date) return value.toLocaleDateString();
      return String(value);
    })
  );

  // Calculate column styles
  const columnStyles: any = {};
  columns.forEach((col, index) => {
    if (col.width) {
      columnStyles[index] = { cellWidth: col.width };
    }
  });

  // Add table with professional styling
  doc.autoTable({
    startY: subtitle ? 90 : 85,
    head: [tableColumns],
    body: tableData,
    theme: 'striped',
    headStyles: {
      fillColor: headerColor,
      textColor: 255,
      fontStyle: 'bold',
      fontSize: 10
    },
    styles: {
      fontSize: 9,
      cellPadding: 3
    },
    columnStyles: columnStyles,
    alternateRowStyles: {
      fillColor: [245, 245, 245]
    }
  });

  // Add summary statistics if provided
  if (summaryStats && summaryStats.length > 0) {
    const finalY = (doc as any).lastAutoTable.finalY || 100;

    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('Summary Statistics:', 20, finalY + 20);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');

    let summaryY = finalY + 30;
    let summaryX = 20;
    const columnWidth = 100;

    summaryStats.forEach((stat, index) => {
      // Create two columns of statistics
      if (index > 0 && index % 6 === 0) {
        summaryY = finalY + 30;
        summaryX += columnWidth;
      }

      const statText = `${stat.label}: ${stat.value}`;
      doc.text(statText, summaryX, summaryY);
      summaryY += 8;
    });
  }

  // Add footer with page numbers
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(128, 128, 128);
    
    const footerText = `Page ${i} of ${pageCount} | Generated by ${companySettings.companyName || 'Asset Management System'}`;
    const pageWidth = doc.internal.pageSize.getWidth();
    const textWidth = doc.getTextWidth(footerText);
    
    doc.text(
      footerText,
      (pageWidth - textWidth) / 2,
      doc.internal.pageSize.getHeight() - 10
    );
  }

  // Save the PDF with timestamped filename
  const timestamp = new Date().toISOString().split('T')[0];
  const sanitizedTitle = title.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '');
  const fileName = `${sanitizedTitle}-${timestamp}.pdf`;
  
  doc.save(fileName);
  logger.info(`PDF report generated: ${fileName}`);
};

/**
 * Helper function to format currency values
 */
export const formatCurrency = (value: number, currency: string = 'USD'): string => {
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: currency
  }).format(value);
};

/**
 * Helper function to format percentages
 */
export const formatPercentage = (value: number, decimals: number = 1): string => {
  return `${value.toFixed(decimals)}%`;
};